services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Mount the local SQLite database into the container for persistence
      # This is for development. In production, you'd connect to a managed database.
      - ./backend/rebirth_game.db:/app/backend/rebirth_game.db
