services:
  - name: rebirth-game-backend
    type: web
    env: docker
    plan: free
    healthCheckPath: /story/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DOUBAO_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

  - name: rebirth-game-frontend
    type: web
    runtime: static
    rootDir: frontend-web
    buildCommand: |
      npm install && npm run build -- --debug
      sed -i "s|%VITE_PUBLIC_SUPABASE_URL%|$VITE_PUBLIC_SUPABASE_URL|g" build/test.html
      sed -i "s|%VITE_PUBLIC_SUPABASE_ANON_KEY%|$VITE_PUBLIC_SUPABASE_ANON_KEY|g" build/test.html
    staticPublishPath: build
    envVars:
      # 将后端服务的 host (域名) 注入到前端构建环境中
      - key: VITE_PUBLIC_API_HOST
        fromService:
          type: web
          name: rebirth-game-backend
          property: host
      - key: VITE_PUBLIC_SUPABASE_URL
        sync: false
      - key: VITE_PUBLIC_SUPABASE_ANON_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
