services:
  - type: web
    name: rebirth-game-backend
    runtime: docker
    healthCheckPath: /health # 使用更简洁、兼容性更好的健康检查路径
    envVars:
      # 以下密钥将在 Render 仪表盘中提示你手动输入
      - key: DATABASE_URL
        sync: false
      - key: DOUBAO_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
