services:
  - name: rebirth-game-backend
    type: web
    env: docker
    plan: free
    healthCheckPath: /story/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DOUBAO_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

  - name: rebirth-game-frontend
    type: static
    env: static
    plan: free
    rootDir: frontend-web
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: VITE_PUBLIC_API_URL
        fromService:
          type: web
          name: rebirth-game-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
