services:
  - type: web
    name: rebirth-game-backend
    runtime: docker
    plan: free
    healthCheckPath: /story/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DOUBAO_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

  - type: static site
    name: rebirth-game-frontend
    plan: free
    rootDir: frontend-web
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      # 将后端服务的URL注入到前端构建环境中
      - key: VITE_PUBLIC_API_URL
        fromService:
          type: web
          name: rebirth-game-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
